### ISSUE TITLE
Excluded shares are not excluded instead .Recycle folder is created (.Recycle vs .Recycle.Bin)

### ISSUE THREAD

**Issue by lolfonfire** [dlandon/recycle.bin#5]
When I exclude a share and delete files it still goes to the bin.

Without excluding a share the Recyle Bin plugin works as expected.
But I only want to enable recycle bin on 1 share. So I started excluding shares.
As soon when I did this and next I delete files on the exluded shares I see a ".Recycle" folder.
- Using the plugin without excluding shares => ".Recycle.Bin" folder
- Using the plugin with excluded shares => ".Recycle" folder

Unraid version: 6.12.4
Recycle Bin plugin version: 2023.08.12

**Comment by dlandon** [comment]
> Using the plugin with excluded shares => ".Recycle" folder

The resycle bin does not create a folder called "Recycle".

Go to a command line and type 'testparm -v'.  This will list the shares and any excluded shares will not have any recycle bin settings.

The excluded shares are case sensitive and you seprate them with commas in the Recycle Bin settings.

**Comment by lolfonfire** [comment]
This is the output of "testparm-v":

[DOWNLOADS]
        path = /mnt/user/DOWNLOADS
        valid users = secretadminuser
        write list = secretadminuser


[PHOTO]
        path = /mnt/user/PHOTO
        valid users = secretadminuser secretnormaluser
        write list = secretadminuser secretnormaluser

[VIDEO]
        path = /mnt/user/VIDEO
        read list = secretnormaluser
        valid users = secretadminuser secretnormaluser
        write list = secretadminuser

[BACKUPS]
        browseable = No
        path = /mnt/user/BACKUPS
        valid users = secretadminuser
        vfs objects = recycle
        write list = secretadminuser
        recycle:exclude_dir = .Recycle.Bin
        recycle:exclude = *.tmp
        recycle:versions = Yes
        recycle:minsize = 1
        recycle:touch_mtime = No
        recycle:touch = Yes
        recycle:keeptree = Yes
        recycle:directory_mode = 0777
        recycle:repository = .Recycle.Bin
        
        As shown in the pictures I've excluded shares "PHOTO", "VIDEO" and "DOWNLOADS" shares but when deleting a file a ".Recycle" folder shows up. And in this recycle folder the deleted file is stored.
        It seems that this happened to VIDEO/PHOTO shares but not on the DOWNLOADS share.
        I've also attached a video demonstrating this.
        
![Exluded_Shares](https://github.com/dlandon/recycle.bin/assets/50797554/1680fb39-bf43-48b4-872d-44cd140cef15)
![Recycle example](https://github.com/dlandon/recycle.bin/assets/50797554/80c1560b-12a0-492b-bcb6-bcf1ef6c781b)
https://github.com/dlandon/recycle.bin/assets/50797554/8461fc94-8714-478f-8552-64c461534c50

**Comment by dlandon** [comment]
I don't see and issue on my server.  We need to see if something unique to your system is causing the issue.

Post your diagnostic on the forum or PM them to me.  Don't post on GitHub.  Let's carry on this discussion there.  I don't see anything so far that would be a bug,

**Comment by lolfonfire** [comment]
I've restarted my UnRaid server and this fixed the issue.
I've excluded all shares except one share. This one share has the .Recycle.Bin when deleting a file.
I don't see any .Recyle folders showing up anymore.
